# -*- coding: utf-8 -*-
"""calculator with oop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sfGqKniSVidds79_aUx-5uFv_21JtvX
"""

class calculator:

  def __init__(self):
    pass

  def add(self, a, b):
    return a+b

  def subtraction(self, a, b):
    return a-b

  def multiply(self, a, b):
    return a*b

  def divide(self, a, b):
    if b == 0:
      return "can't be divided by 0"
    else:
      return a/b

      # import math

      # def sin_math(self, a):
          # print(math.sin())

my_calculator = calculator()

result = my_calculator.add(20, 40)
print(result)
result = my_calculator.subtraction(40, 20)
print(result)
result = my_calculator.multiply(10, 30)
print(result)
result = my_calculator.divide(10, 5)
print(result)
result = my_calculator.divide(10,0)
print(result)
# result = my_calculator.sin_math(15)
# print(result)

class calculator2(calculator):
  def __init__(self):
   super().__init__(self)

  def add(self, a, b):
    return a+b

  def subtraction(calculator, a, b):
    return a-b

  def multiply(calculator, a, b):
     return a*b

  def divide(calculator, a, b):
    pass

my_calculator = calculator()

result = my_calculator.add(30, 70)
print(result)
result = my_calculator.subtraction(60, 20)
print(result)
result = my_calculator.multiply(20, 5)
print(result)
result = my_calculator.divide(10, 5)
print(result)
result = my_calculator.divide(20,0)
print(result)